canIds = {
'ID284' : [{'name':'Left Wheel Speed', 'coeff':0.0031068636832491, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'Right Wheel Speed', 'coeff':0.0031068636832491, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'Vehicle Speed', 'coeff':0.0062137273664981, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False}],
'ID5A9' : [{'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'Range', 'coeff':0.00775335775336, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False}],
'ID1db' : [{},
           {},
           {},
           {},
           {},
           {},
           {},
           {}]
}