canIds = {
'ID1DB' : [{'name':'Battery Current Signal', 'coeff':0.5,'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'Battery Voltage Signal', 'coeff':0.5,'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False}],
'ID284' : [{'name':'Left Wheel Speed', 'coeff':0.0031068636832491, 'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'Right Wheel Speed', 'coeff':0.0031068636832491, 'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'Vehicle Speed', 'coeff':0.0062137273664981, 'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False}],
'ID5A9' : [{'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'Range', 'coeff':0.00775335775336, 'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False}],
'ID5BC' : [{'name':'Available Charge Signal', 'coeff':0.00002775, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False}],
'ID55B' : [{'name':'State of Charge', 'coeff':0.000027753108348, 'highlow':True},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False},
    {'name':'NA', 'coeff':0, 'highlow':False}],

}
