canIds = {
'ID284' : [{'name':'Left Wheel Speed', 'coeff':0.0031068636832491, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'Right Wheel Speed', 'coeff':0.0031068636832491, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'Vehicle Speed', 'coeff':0.0062137273664981, 'highlow':True},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False},
         {'name':'NA', 'coeff':0, 'highlow':False}],
'ID1da' : [{},
           {},
           {},
           {},
           {},
           {},
           {},
           {}],
'ID1db' : [{},
           {},
           {},
           {},
           {},
           {},
           {},
           {}]
}